apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-rep
spec:
  replicas: 1
  selector:
    app: selenium-firefox
  template:
    metadata:
      name: selenium-firefox
      labels:
        app: selenium-firefox
    spec:
      containers:
        - name: node-firefox
          image: selenium/node-firefox
          ports:
            - containerPort: 5900
          env:
            - name: HUB_HOST
              value: "selenium-srv"
            - name: HUB_PORT
              value: "4444"